[tools]
dotnet = "latest"
go = "1.25.1"
node = "25.9.0"
opentofu = "latest"
pnpm = "12.3.4"
ruby = "3.4.7"
terraform = "latest"
uv = "latest"
java = "21"
postgres = "latest"
"npm:lavish-axi" = "0.1.50"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"gem:ruby-lsp" = "0.26.11"

[settings]

[settings.node]
