lastChangelogVersion: 14.1.2
modelRoles: 
  default: anthropic-vertex/claude-opus-4-6
  task: anthropic-vertex/claude-sonnet-4-6
  commit: anthropic-vertex/claude-haiku-4-5
theme: 
  dark: dark-tokyo-night
statusLine: 
  preset: default
  separator: powerline-thin
display: 
  showTokenUsage: true
showHardwareCursor: true
symbolPreset: nerd