#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# Owners given a token during this run. Guards the clobber that `-U` invites:
# name the same owner at two stages and the second token silently replaces the
# first, leaving one owner unreachable and no sign of it.
STORED_OWNERS=()

# One token per GitHub resource owner, because a fine-grained PAT has exactly
# one. Stored in the login keychain under service "gh-readonly", keyed by owner
# login, which is what ~/.local/bin/gh looks up. Never write_env: this repo is
# public, and a token in a file is a token in every backup.
store_token() {
  local owner="$1" token="$2" seen
  if [ -z "$owner" ] || [ -z "$token" ]; then
    [ -n "$owner" ] && { SKIPPED+=("read-only token for $owner"); warn "no token entered for $owner, skipping"; }
    return 0
  fi
  for seen in ${STORED_OWNERS+"${STORED_OWNERS[@]}"}; do
    if [ "$seen" = "$owner" ]; then
      warn "you already stored a token for $owner in this run."
      note "  Each owner holds exactly one token, so saving this would discard that one."
      note "  An org token belongs under the ORG's login, never under your username."
      SKIPPED+=("read-only token for $owner (duplicate owner, not stored)")
      return 1
    fi
  done
  if security add-generic-password -U -s gh-readonly -a "$owner" -w "$token" \
       -D "GitHub read-only PAT" 2>/dev/null; then
    STORED_OWNERS+=("$owner")
    printf '  %s✓ stored%s read-only token for %s\n' "$GREEN" "$RESET" "$owner"
  else
    SKIPPED+=("read-only token for $owner (keychain write failed)")
    warn "could not write the keychain entry for $owner"
  fi
  return 0
}

has_token() { security find-generic-password -s gh-readonly -a "$1" -w >/dev/null 2>&1; }

# Owner logins already checked out on this machine. Stage 3 needs an exact
# login, and reading it off a remote beats recalling it.
suggest_owners() {
  local d url
  for d in "$HOME"/dev/*/.git "$HOME"/dev/*/*/.git; do
    [ -d "$d" ] || continue
    url=$(git -C "${d%/.git}" config --get remote.origin.url 2>/dev/null) || true
    case "$url" in *github*) printf '%s\n' "$url" ;; esac
  done | sed -E 's#\.git$##; s#.*[:/]([^/]+)/[^/]+$#\1#' | sort -u
}

permissions_recipe() {
  step "Repository access: All repositories."
  step "Repository permissions, every one set to Read-only: Contents, Metadata,"
  say  "    Pull requests, Issues, Actions, Commit statuses, Workflows."
  step "Leave every Account permission at No access."
  step "Expiration: whatever you'll tolerate re-running this wizard for."
}

# One stage per owner, all shaped the same: name the owner, mint a token whose
# resource owner is that exact login, paste it. Returns non-zero when nothing
# was stored, which the org loop uses to re-ask.
collect_for_owner() {
  local owner="$1" token
  # Ask before opening anything. A re-run to add one owner should not spray a
  # new-token page per stage for the owners you are keeping.
  if has_token "$owner"; then
    note "$owner already has a token."
    if ! confirm "Replace the token for $owner?"; then
      note "kept the existing token for $owner"
      return 0
    fi
  fi
  open_url "https://github.com/settings/personal-access-tokens/new"
  step "Resource owner: $owner. That dropdown is the whole point of this stage."
  permissions_recipe
  ask_secret token "Paste the token whose resource owner is $owner:"
  if [ -z "$token" ]; then
    if has_token "$owner"; then note "kept the existing token for $owner"; return 0; fi
    SKIPPED+=("read-only token for $owner")
    warn "no token entered for $owner, skipping"
    return 0
  fi
  store_token "$owner" "$token"
}

banner "GitHub read-only tokens for ~/.local/bin/gh"

stage "Your personal account"
say "A fine-grained token that reads your own repos and nothing else."
ask PERSONAL_OWNER "Personal login [tvrmsmith]:"
PERSONAL_OWNER="${PERSONAL_OWNER:-tvrmsmith}"
collect_for_owner "$PERSONAL_OWNER"

stage "Your work user account"
say "Repos owned by your work login. An org's repos are a separate owner and a"
say "separate stage, so this token reaches nothing the org owns."
ask WORK_OWNER "Work login [TrevorSmith-Wellsky]:"
WORK_OWNER="${WORK_OWNER:-TrevorSmith-Wellsky}"
collect_for_owner "$WORK_OWNER"

stage "Organisations"
say "One token per org whose repos you read. The login you type here is the org's"
say "own login, the owner segment of a remote like git@github.com:ORG/repo.git."
warn "Your own username is NOT an org. It had its own stage above."
say ""
CANDIDATES=$(suggest_owners | grep -vxF -e "$PERSONAL_OWNER" -e "$WORK_OWNER" || true)
if [ -n "$CANDIDATES" ]; then
  say "Owners found in the remotes on this machine:"
  while IFS= read -r c; do
    [ -n "$c" ] || continue
    if has_token "$c"; then note "  $c (already has a token)"; else step "$c"; fi
  done <<< "$CANDIDATES"
  say ""
fi
warn "An org may require an owner to approve the token before it works."
note "  Re-run this wizard once approval lands; that org keeps prompting until then."
while true; do
  ask ORG_OWNER "Org login, or type done to move on:"
  case "$ORG_OWNER" in "" | done | Done | DONE) break ;; esac
  collect_for_owner "$ORG_OWNER" || pause "Press Enter to try again."
done

# Prove the scope, not the routing. Reading a repo shows the token reaches the
# owner; a 403 on POST git/blobs shows it cannot write there. The blob is
# unreferenced, so it touches no branch and GitHub garbage-collects it, which
# makes this the one write GitHub offers that is safe to fire at a live repo.
verify_owner() {
  local owner="$1" token repo status
  token=$(security find-generic-password -s gh-readonly -a "$owner" -w 2>/dev/null) || {
    warn "$owner: no token stored, so its reads still prompt"; return; }
  repo=$(GH_TOKEN="$token" gh api "/user/repos?per_page=100&affiliation=owner,organization_member" \
           --jq ".[] | select(.owner.login == \"$owner\") | .full_name" 2>/dev/null | head -1)
  if [ -z "$repo" ]; then
    warn "$owner: token stored, but it can see no repo owned by $owner."
    note "  Its resource owner is probably a different login, or the org has not approved it."
    return
  fi
  status=$(GH_TOKEN="$token" gh api -X POST "/repos/$repo/git/blobs" \
             -f content=probe -f encoding=utf-8 --silent -i 2>/dev/null | head -1)
  case "$status" in
    *403*) printf '  %s✓ %s%s reads %s, cannot write it\n' "$GREEN" "$owner" "$RESET" "$repo" ;;
    *)     warn "$owner: the write probe on $repo returned '${status:-no response}', not 403."
           note "  A success means the token is over-scoped; regenerate it with read-only permissions." ;;
  esac
}

stage "Verify"
say "Routing first. A read prints 'read <owner>', a write prints 'write'."
GH_SHIM_EXPLAIN=1 "$HOME/.local/bin/gh" pr list || true
GH_SHIM_EXPLAIN=1 "$HOME/.local/bin/gh" pr merge 1 || true
say ""
say "Now the scope of each token stored, which is the check that matters."
for OWNER in ${STORED_OWNERS+"${STORED_OWNERS[@]}"}; do verify_owner "$OWNER"; done
if [ -z "${STORED_OWNERS+x}" ]; then note "nothing stored this run, so nothing to verify."; fi
pause "Press Enter to finish."

finish
