#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Two kinds of token, each its own keychain service, each keyed by owner login.
# gh-readonly is read-only everywhere. gh-prwrite adds `Pull requests: write`
# and nothing else, so it opens PRs and cannot merge one: GitHub gates merging
# on `Contents: write`, which this token does not have. See dotfiles-jwp.
#
# Kept as separate tokens rather than one combined token so that a command the
# shim misclassifies as a read still cannot write. That property is why the
# read tier can safely borrow a token across owners.
KIND_SERVICE() { case "$1" in pr) echo gh-prwrite ;; *) echo gh-readonly ;; esac; }
KIND_LABEL()   { case "$1" in pr) echo "PR-write" ;; *) echo "read-only" ;; esac; }

# Owners given a token during this run, one list per kind. Guards the clobber
# that `-U` invites: name the same owner at two stages and the second token
# silently replaces the first, leaving one owner unreachable and no sign of it.
STORED_OWNERS=()
STORED_PR_OWNERS=()
OWNERS_SEEN=()

already_stored() {
  local kind="$1" owner="$2" seen
  case "$kind" in
    pr) for seen in ${STORED_PR_OWNERS+"${STORED_PR_OWNERS[@]}"}; do
          [ "$seen" = "$owner" ] && return 0; done ;;
    *)  for seen in ${STORED_OWNERS+"${STORED_OWNERS[@]}"}; do
          [ "$seen" = "$owner" ] && return 0; done ;;
  esac
  return 1
}

# One token per GitHub resource owner per kind, because a fine-grained PAT has
# exactly one resource owner. Never write_env: this repo is public, and a token
# in a file is a token in every backup.
store_token() {
  local owner="$1" token="$2" kind="${3:-read}" service label
  service=$(KIND_SERVICE "$kind"); label=$(KIND_LABEL "$kind")
  if [ -z "$owner" ] || [ -z "$token" ]; then
    [ -n "$owner" ] && { SKIPPED+=("$label token for $owner"); warn "no token entered for $owner, skipping"; }
    return 0
  fi
  if already_stored "$kind" "$owner"; then
    warn "you already stored a $label token for $owner in this run."
    note "  Each owner holds exactly one token of each kind, so saving this would discard that one."
    note "  An org token belongs under the ORG's login, never under your username."
    SKIPPED+=("$label token for $owner (duplicate owner, not stored)")
    return 1
  fi
  if security add-generic-password -U -s "$service" -a "$owner" -w "$token" \
       -D "GitHub $label PAT" 2>/dev/null; then
    case "$kind" in
      pr) STORED_PR_OWNERS+=("$owner") ;;
      *)  STORED_OWNERS+=("$owner") ;;
    esac
    printf '  %s✓ stored%s %s token for %s\n' "$GREEN" "$RESET" "$label" "$owner"
  else
    SKIPPED+=("$label token for $owner (keychain write failed)")
    warn "could not write the keychain entry for $owner"
  fi
  return 0
}

has_token() {
  security find-generic-password -s "$(KIND_SERVICE "${2:-read}")" -a "$1" -w >/dev/null 2>&1
}

# Every owner this run named, whatever came of it. Stage 4 offers a PR token for
# each rather than asking you to retype the logins.
remember_owner() {
  local owner="$1" seen
  for seen in ${OWNERS_SEEN+"${OWNERS_SEEN[@]}"}; do [ "$seen" = "$owner" ] && return 0; done
  OWNERS_SEEN+=("$owner")
}

# Who stage 4 offers. OWNERS_SEEN alone is wrong on a re-run: stage 3 only names
# an org when you type one, so keeping every existing token and answering "done"
# left the orgs out of the PR stage entirely. Recover them from the owners that
# already hold a read token on this machine.
pr_stage_owners() {
  local owner
  {
    for owner in ${OWNERS_SEEN+"${OWNERS_SEEN[@]}"}; do printf '%s\n' "$owner"; done
    suggest_owners | while IFS= read -r owner; do
      [ -n "$owner" ] || continue
      has_token "$owner" && printf '%s\n' "$owner"
    done
  } | awk '!seen[$0]++'
}

# Owner logins already checked out on this machine. Stage 3 needs an exact
# login, and reading it off a remote beats recalling it.
suggest_owners() {
  local d url
  for d in "$HOME"/dev/*/.git "$HOME"/dev/*/*/.git; do
    [ -d "$d" ] || continue
    url=$(git -C "${d%/.git}" config --get remote.origin.url 2>/dev/null) || true
    case "$url" in *github*) printf '%s\n' "$url" ;; esac
  done | sed -E 's#\.git$##; s#.*[:/]([^/]+)/[^/]+$#\1#' | sort -u
}

permissions_recipe() {
  case "$1" in
    pr)
      step "Repository access: All repositories."
      step "Repository permissions: set Pull requests to ${BOLD}Read and write${RESET}."
      step "Set Contents, Metadata, Issues, Actions, Commit statuses to Read-only."
      warn "Contents MUST stay Read-only. That is the whole gate."
      note "  Merging a PR needs Contents: write, and so does enabling auto-merge."
      note "  Leave it at read and this token cannot merge anything, by any route."
      step "Leave every Account permission at No access."
      ;;
    *)
      step "Repository access: All repositories."
      step "Repository permissions, every one set to Read-only: Contents, Metadata,"
      say  "    Pull requests, Issues, Actions, Commit statuses, Workflows."
      note "  There is no Checks permission to grant, so do not go looking for one."
      note "  GitHub withdrew it from fine-grained tokens; only GitHub Apps and"
      note "  classic tokens reach the Checks API. That is why \`gh pr checks\` fails"
      note "  on a private repo with 'Resource not accessible by personal access"
      note "  token', and why Actions and Commit statuses above are load-bearing."
      step "Leave every Account permission at No access."
      ;;
  esac
  step "Expiration: whatever you'll tolerate re-running this wizard for."
}

# Name the owner, mint a token whose resource owner is that exact login, paste
# it. Returns non-zero when nothing was stored, which the org loop uses to
# re-ask.
collect_for_owner() {
  local owner="$1" kind="${2:-read}" token label
  label=$(KIND_LABEL "$kind")
  remember_owner "$owner"
  # Ask before opening anything. A re-run to add one owner should not spray a
  # new-token page per stage for the owners you are keeping.
  if has_token "$owner" "$kind"; then
    note "$owner already has a $label token."
    if ! confirm "Replace the $label token for $owner?"; then
      note "kept the existing $label token for $owner"
      return 0
    fi
  fi
  open_url "https://github.com/settings/personal-access-tokens/new"
  step "Resource owner: $owner. That dropdown is the whole point of this stage."
  permissions_recipe "$kind"
  ask_secret token "Paste the $label token whose resource owner is $owner:"
  if [ -z "$token" ]; then
    if has_token "$owner" "$kind"; then note "kept the existing $label token for $owner"; return 0; fi
    SKIPPED+=("$label token for $owner")
    warn "no $label token entered for $owner, skipping"
    return 0
  fi
  store_token "$owner" "$token" "$kind"
}

# ── The write tier's owner → 1Password map ────────────────────────────────
#
# The third tier holds no token of its own: it reads one from 1Password at the
# moment you approve. It still needs to know WHICH 1Password item, because
# `op plugin run` cannot be told, and left to itself it authenticated a personal
# merge as the work user. So the owner decides, from this map. See dotfiles-4ul.
#
# Not the keychain, unlike the other two tiers. Nothing secret is stored here,
# only the coordinates of something secret, and the shim wants them readable
# without a keychain prompt of its own.
WRITE_MAP="${WRITE_MAP:-${XDG_CONFIG_HOME:-$HOME/.config}/gh-shim/write-tokens}"

# "owner account op://..." rows this run settled on, whether typed or kept.
WRITE_ROWS=()

answered_write() {
  local want="$1" row
  for row in ${WRITE_ROWS+"${WRITE_ROWS[@]}"}; do
    [ "${row%% *}" = "$want" ] && return 0
  done
  return 1
}

# Prints "account op://..." for an owner already in the map, or fails. A field
# may hold spaces (item names do), so only the gaps between fields normalise.
write_row_for() {
  local want="$1" owner account ref
  [ -f "$WRITE_MAP" ] || return 1
  while read -r owner account ref; do
    case "$owner" in '' | '#'*) continue ;; esac
    [ "$owner" = "$want" ] || continue
    [ -n "$account" ] && [ -n "$ref" ] || continue
    printf '%s %s\n' "$account" "$ref"
    return 0
  done < "$WRITE_MAP"
  return 1
}

collect_write_for_owner() {
  local owner="$1" current
  current=$(write_row_for "$owner" || true)
  if [ -n "$current" ]; then
    note "$owner currently reads its write token from: $current"
    if ! confirm "Replace that for $owner?"; then
      WRITE_ROWS+=("$owner $current")
      note "kept the existing entry for $owner"
      return 0
    fi
  fi
  ask WRITE_ACCOUNT "1Password account for $owner (the URL column of \`op account list\`):"
  ask WRITE_REF "Secret reference to its token field (op://vault/item/field):"
  if [ -z "$WRITE_ACCOUNT" ] || [ -z "$WRITE_REF" ]; then
    [ -n "$current" ] && { WRITE_ROWS+=("$owner $current"); note "kept the existing entry for $owner"; return 0; }
    SKIPPED+=("write-token mapping for $owner")
    warn "nothing entered for $owner, so its writes keep guessing an account"
    return 0
  fi
  # A bad reference fails at approval time, hours later, as an opaque op error.
  # Catching the shape here costs one line and turns that into a retype.
  case "$WRITE_REF" in
    op://*/*/*) ;;
    *) warn "that is not an op:// reference with a vault, item and field."
       return 1 ;;
  esac
  case "$WRITE_ACCOUNT" in
    *[[:space:]]*) warn "an account URL has no spaces in it."; return 1 ;;
  esac
  WRITE_ROWS+=("$owner $WRITE_ACCOUNT $WRITE_REF")
  printf '  %s✓ mapped%s %s → %s\n' "$GREEN" "$RESET" "$owner" "$WRITE_ACCOUNT"
  return 0
}

# Rewrites the whole map. Owners this run never asked about keep the line they
# already had, so adding one owner does not drop the rest.
write_map_flush() {
  local dir tmp owner account ref
  if [ -z "${WRITE_ROWS+x}" ]; then
    note "no owners mapped, so $WRITE_MAP is left as it is"
    return 0
  fi
  dir=$(dirname "$WRITE_MAP")
  mkdir -p "$dir"
  tmp=$(mktemp "$dir/.write-tokens.XXXXXX")
  chmod 600 "$tmp"
  {
    printf '# owner  1password-account  op://vault/item/field\n'
    printf '# Written by extras/gh-readonly-tokens.sh. Read by dot-local/bin/gh.\n'
    if [ -f "$WRITE_MAP" ]; then
      while read -r owner account ref; do
        case "$owner" in '' | '#'*) continue ;; esac
        [ -n "$account" ] && [ -n "$ref" ] || continue
        answered_write "$owner" && continue
        printf '%s %s %s\n' "$owner" "$account" "$ref"
      done < "$WRITE_MAP"
    fi
    printf '%s\n' "${WRITE_ROWS[@]}"
  } > "$tmp"
  mv "$tmp" "$WRITE_MAP"
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$WRITE_MAP"
}

banner "GitHub tokens for ~/.local/bin/gh"

stage "Your personal account"
say "A fine-grained token that reads your own repos and nothing else."
ask PERSONAL_OWNER "Personal login [tvrmsmith]:"
PERSONAL_OWNER="${PERSONAL_OWNER:-tvrmsmith}"
collect_for_owner "$PERSONAL_OWNER"

stage "Your work user account"
say "Repos owned by your work login. An org's repos are a separate owner and a"
say "separate stage, so this token reaches nothing the org owns."
ask WORK_OWNER "Work login [TrevorSmith-Wellsky]:"
WORK_OWNER="${WORK_OWNER:-TrevorSmith-Wellsky}"
collect_for_owner "$WORK_OWNER"

stage "Organisations"
say "One token per org whose repos you read. The login you type here is the org's"
say "own login, the owner segment of a remote like git@github.com:ORG/repo.git."
warn "Your own username is NOT an org. It had its own stage above."
say ""
CANDIDATES=$(suggest_owners | grep -vxF -e "$PERSONAL_OWNER" -e "$WORK_OWNER" || true)
if [ -n "$CANDIDATES" ]; then
  say "Owners found in the remotes on this machine:"
  while IFS= read -r c; do
    [ -n "$c" ] || continue
    if has_token "$c"; then note "  $c (already has a token)"; else step "$c"; fi
  done <<< "$CANDIDATES"
  say ""
fi
warn "An org may require an owner to approve the token before it works."
note "  Re-run this wizard once approval lands; that org keeps prompting until then."
while true; do
  ask ORG_OWNER "Org login, or type done to move on:"
  case "$ORG_OWNER" in "" | done | Done | DONE) break ;; esac
  collect_for_owner "$ORG_OWNER" || pause "Press Enter to try again."
done

stage "PR tokens"
say "A second token per owner so agents can open PRs without asking you, while"
say "merging still waits for your 1Password approval."
say ""
say "This is not a policy the shim enforces, it is what the token can do. GitHub"
say "gates opening a PR on Pull requests: write, and merging on Contents: write."
say "Grant the first, withhold the second, and merge is closed off entirely."
say ""
note "Skip any owner you don't want agents opening PRs against. A skipped owner"
note "  just means opening a PR there keeps prompting, same as today."
say ""
for OWNER in $(pr_stage_owners); do
  if confirm "Add a PR-write token for $OWNER?"; then
    collect_for_owner "$OWNER" pr || pause "Press Enter to continue."
  else
    note "skipped $OWNER; its PR creation keeps prompting"
  fi
done

# The list above comes from this run and from this machine's remotes, so an org
# whose repos are not cloned here appears in neither. Ask, rather than making
# that owner wait for the next re-run.
say ""
while true; do
  ask EXTRA_OWNER "Another owner to add a PR token for, or done:"
  case "$EXTRA_OWNER" in "" | done | Done | DONE) break ;; esac
  collect_for_owner "$EXTRA_OWNER" pr || pause "Press Enter to try again."
done

# Prove the scope, not the routing. Reading a repo shows the token reaches the
# owner; a 403 on POST git/blobs shows it cannot write there. The blob is
# unreferenced, so it touches no branch and GitHub garbage-collects it, which
# makes this the one write GitHub offers that is safe to fire at a live repo.
verify_owner() {
  local owner="$1" token repo status
  token=$(security find-generic-password -s gh-readonly -a "$owner" -w 2>/dev/null) || {
    warn "$owner: no token stored, so its reads still prompt"; return; }
  repo=$(GH_TOKEN="$token" gh api "/user/repos?per_page=100&affiliation=owner,organization_member" \
           --jq ".[] | select(.owner.login == \"$owner\") | .full_name" 2>/dev/null | head -1)
  if [ -z "$repo" ]; then
    warn "$owner: token stored, but it can see no repo owned by $owner."
    note "  Its resource owner is probably a different login, or the org has not approved it."
    return
  fi
  status=$(GH_TOKEN="$token" gh api -X POST "/repos/$repo/git/blobs" \
             -f content=probe -f encoding=utf-8 --silent -i 2>/dev/null | head -1)
  case "$status" in
    *403*) printf '  %s✓ %s%s reads %s, cannot write it\n' "$GREEN" "$owner" "$RESET" "$repo" ;;
    *)     warn "$owner: the write probe on $repo returned '${status:-no response}', not 403."
           note "  A success means the token is over-scoped; regenerate it with read-only permissions." ;;
  esac
  verify_checks_read "$owner" "$token" "$repo"
}

# A token can read every repo and still not say whether CI passed. No fine-
# grained token reads the Checks API on a private repo: GitHub withdrew that
# permission, leaving it to GitHub Apps and classic tokens (community
# discussion 129512). So a 403 here is not something to fix on the token, and
# the probe exists to say so, because `gh pr checks` itself reports it as ten
# GraphQL "Resource not accessible" lines naming node paths.
#
# The two endpoints it CAN reach, commit statuses and Actions runs, together
# cover the same ground. That is what the Actions and Commit statuses
# permissions above are for.
verify_checks_read() {
  local owner="$1" token="$2" repo="$3" runs statuses actions
  runs=$(GH_TOKEN="$token" gh api "/repos/$repo/commits/HEAD/check-runs" --silent -i 2>/dev/null | head -1)
  statuses=$(GH_TOKEN="$token" gh api "/repos/$repo/commits/HEAD/status" --silent -i 2>/dev/null | head -1)
  actions=$(GH_TOKEN="$token" gh api "/repos/$repo/actions/runs?per_page=1" --silent -i 2>/dev/null | head -1)
  case "$runs" in *403*)
    note "$owner: no Checks API, as expected on a fine-grained token."
    note "  \`gh pr checks\` fails on this owner's private repos. Nothing to fix." ;;
  esac
  case "$statuses" in *403*)
    warn "$owner: cannot read commit statuses, which IS grantable."
    note "  Add Commit statuses: Read-only to this token." ;;
  esac
  case "$actions" in *403*)
    warn "$owner: cannot read Actions runs, which IS grantable."
    note "  Add Actions: Read-only to this token." ;;
  esac
}

# The PR token has to clear two bars: it can open a PR, and it cannot merge one.
#
# For the first, POST a PR with a head branch that does not exist. GitHub checks
# permission before it validates the body, so 422 means authorised and 403 means
# not, and either way no PR is created. For the second, reuse the blob probe:
# merging needs Contents: write, so a 403 from POST git/blobs proves the token
# cannot merge without going anywhere near a real merge.
verify_pr_owner() {
  local owner="$1" token repo create_status blob_status
  token=$(security find-generic-password -s gh-prwrite -a "$owner" -w 2>/dev/null) || {
    note "$owner: no PR token, so opening a PR there still prompts"; return; }
  repo=$(GH_TOKEN="$token" gh api "/user/repos?per_page=100&affiliation=owner,organization_member" \
           --jq ".[] | select(.owner.login == \"$owner\") | .full_name" 2>/dev/null | head -1)
  if [ -z "$repo" ]; then
    warn "$owner: PR token stored, but it can see no repo owned by $owner."
    note "  Its resource owner is probably a different login, or the org has not approved it."
    return
  fi
  create_status=$(GH_TOKEN="$token" gh api -X POST "/repos/$repo/pulls" \
                    -f title=probe -f head=gh-wizard-probe-does-not-exist -f base=main \
                    --silent -i 2>/dev/null | head -1)
  blob_status=$(GH_TOKEN="$token" gh api -X POST "/repos/$repo/git/blobs" \
                  -f content=probe -f encoding=utf-8 --silent -i 2>/dev/null | head -1)
  case "$create_status" in
    *422*) ;;
    *403*) warn "$owner: the PR token cannot open a PR on $repo (403)."
           note "  Set Pull requests to Read and write and re-run."; return ;;
    *)     warn "$owner: the PR probe on $repo returned '${create_status:-no response}'."
           note "  Expected 422 (authorised, bad branch) or 403 (not authorised)."; return ;;
  esac
  case "$blob_status" in
    *403*) printf '  %s✓ %s%s can open PRs on %s, cannot merge them\n' "$GREEN" "$owner" "$RESET" "$repo" ;;
    *)     warn "$owner: the PR token can WRITE CONTENTS on $repo ('${blob_status:-no response}', not 403)."
           note "  That means it can merge. Set Contents back to Read-only and regenerate it." ;;
  esac
}

stage "Write tokens in 1Password"
say "The last tier, the one that prompts. It has no token of its own: on your"
say "approval it reads a full-access token out of 1Password. This stage records"
say "which item, per owner."
say ""
say "It has to be per owner. \`op plugin run\` picks an account by itself, and it"
say "picked the work one for a personal merge, which failed as the wrong user."
say ""
note "Nothing secret is written here, only an op:// reference to the secret."
note "  Right-click the token field in 1Password and Copy Secret Reference."
note "  An owner you skip falls back to that guessing, so map the ones you merge in."
say ""
for OWNER in $(pr_stage_owners); do
  if confirm "Map $OWNER to a 1Password write token?"; then
    collect_write_for_owner "$OWNER" || pause "Press Enter to continue."
  else
    note "skipped $OWNER; its writes keep guessing an account"
  fi
done

say ""
while true; do
  ask EXTRA_WRITE_OWNER "Another owner to map, or done:"
  case "$EXTRA_WRITE_OWNER" in "" | done | Done | DONE) break ;; esac
  collect_write_for_owner "$EXTRA_WRITE_OWNER" || pause "Press Enter to try again."
done
write_map_flush

stage "Verify"
say "Routing first: a read prints 'read <owner>', opening a PR prints"
say "'pr-write <owner>', and anything needing approval prints 'write <owner>'."
GH_SHIM_EXPLAIN=1 "$HOME/.local/bin/gh" pr list || true
GH_SHIM_EXPLAIN=1 "$HOME/.local/bin/gh" pr create --fill || true
GH_SHIM_EXPLAIN=1 "$HOME/.local/bin/gh" pr merge 1 || true
say ""
say "Now the scope of each token stored, which is the check that matters."
for OWNER in ${STORED_OWNERS+"${STORED_OWNERS[@]}"}; do verify_owner "$OWNER"; done
for OWNER in ${STORED_PR_OWNERS+"${STORED_PR_OWNERS[@]}"}; do verify_pr_owner "$OWNER"; done
if [ -z "${STORED_OWNERS+x}" ] && [ -z "${STORED_PR_OWNERS+x}" ]; then
  note "nothing stored this run, so nothing to verify."
fi
pause "Press Enter to finish."

finish
